CUISINE_TYPES = [
  'american',
  'asian',
  'british',
  'caribbean',
  'central europe',
  'chinese',
  'eastern europe',
  'french',
  'greek',
  'indian',
  'italian',
  'japanese',
  'korean',
  'kosher',
  'mediterranean',
  'mexican',
  'middle eastern',
  'nordic',
  'south american',
  'south east asian',
  'world'
]

DISH_TYPES = [
  'alcohol cocktail',
  'biscuits and cookies',
  'bread',
  'cereals',
  'condiments and sauces',
  'desserts',
  'drinks',
  'egg',
  'ice cream and custard',
  'main course',
  'pancake',
  'pasta',
  'pastry',
  'pies and tarts',
  'pizza',
  'preps',
  'preserve',
  'salad',
  'sandwiches',
  'seafood',
  'side dish',
  'soup',
  'special occasions',
  'starter',
  'sweets'
]

MEAL_TYPES = ['breakfast', 'brunch', 'lunch/dinner', 'snack', 'teatime']

HEALTH_LABELS = [
  'alcohol-cocktail',
  'alcohol-free',
  'celery-free',
  'crustacean-free',
  'dairy-free',
  'DASH',
  'egg-free',
  'fish-free',
  'fodmap-free',
  'gluten-free',
  'immuno-supportive',
  'keto-friendly',
  'kidney-friendly',
  'kosher',
  'low-fat-abs',
  'low-potassium',
  'low-sugar',
  'lupine-free',
  'Mediterranean',
  'mollusk-free',
  'mustard-free',
  'no-oil-added',
  'paleo',
  'peanut-free',
  'pescatarian',
  'pork-free',
  'red-meat-free',
  'sesame-free',
  'shellfish-free',
  'soy-free',
  'sugar-conscious',
  'sulfite-free',
  'tree-nut-free',
  'vegan',
  'vegetarian',
  'wheat-free',
]

DIET_LABELS = [
  'balanced',
  'high-fiber',
  'high-protein',
  'low-carb',
  'low-fat',
  'low-sodium',
]
